alias lt='ls -Flth --color=auto'
alias l='ls -Flh --color=auto'
alias la='ls -FAlh --color=auto'
alias p='python3'
alias repos='cd ~/repos'
alias grep='grep --color=auto'
alias pcra='pre-commit run -a'
